[package]
name = "circuit"
type = "bin"
authors = []
compiler_version = ">=1.0.0"

[dependencies]
trees = { git = "https://github.com/privacy-scaling-explorations/zk-kit.noir", tag = "merkle-trees-v0.0.1", directory = "packages/merkle-trees" }
